DATABASE_URL:

GITHUB_CLIENT_ID:
GITHUB_CLIENT_SECRET:

GOOGLE_OAUTH2_CLIENT_ID:
GOOGLE_OAUTH2_CLIENT_SECRET:

MAILGUN_API_KEY:
MAILGUN_DOMAIN:
MAILGUN_PUBLIC_KEY:
MAILGUN_SMTP_LOGIN:
MAILGUN_SMTP_PASSWORD:
MAILGUN_SMTP_PORT:
MAILGUN_SMTP_SERVER:

SLACK_API_TOKEN:
SLACK_CLIENT_ID:
SLACK_CLIENT_SECRET:  
